import {test} from 'node:test';
import assert from 'node:assert/strict';
import {applyOperation,emptyStore,businessDate,isOpen,report,expectedCash,type Operation,type Store} from '../lib/engine.ts';
import {parseInventoryText,parseOrderText,csvCell} from '../lib/intake.ts';
const time='2026-09-10T16:00:00.000Z';let n=0;
function apply(s:Store,type:string,fields:Record<string,unknown>={},at=time){return applyOperation(s,{id:`test-${++n}`,type,...fields},at).state;}
function setup(){return apply(apply(emptyStore(),'seed'),'openShift',{float:10000});}
function order(s:Store,more:Record<string,unknown>={}){return apply(s,'order',{mode:'retail',items:[{productId:'sample-1',qty:2}],confirmed:true,tender:'cash',cashReceived:10000,...more});}
test('cash sale atomically records snapshotted prices, inventory, print and expected drawer',()=>{const s=order(setup());assert.equal(s.orders[0].total,4068);assert.equal(s.products[0].stock,22);assert.equal(s.prints.length,1);assert.equal(expectedCash(s,s.shifts[0]),14068);});
test('retry has one business effect and rejects changed payload with same ID',()=>{const s=setup();const op:Operation={id:'unique-sale',type:'order',mode:'retail',items:[{productId:'sample-1',qty:1}],confirmed:true,tender:'cash',cashReceived:10000};const first=applyOperation(s,op,time);const next=applyOperation(first.state,op,time);assert.equal(next.duplicate,true);assert.deepEqual(next.state,first.state);assert.throws(()=>applyOperation(first.state,{...op,cashReceived:20000}),/another request/);});
test('insufficient stock rejects entire operation and leaves original unchanged',()=>{const s=setup();const before=structuredClone(s);assert.throws(()=>order(s,{items:[{productId:'sample-1',qty:999}]}),/stock/);assert.deepEqual(s,before);});
test('two successive buyers of last item cannot oversell',()=>{let s=setup();s=apply(s,'stock',{productId:'sample-1',count:1,reason:'Count'});s=order(s,{items:[{productId:'sample-1',qty:1}]});assert.throws(()=>order(s,{items:[{productId:'sample-1',qty:1}]}),/stock/);});
test('refund reverses original tax and cannot exceed original quantity',()=>{let s=order(setup());s=apply(s,'refund',{orderId:s.orders[0].id,reason:'Return',items:[{productId:'sample-1',qty:1,restock:true}]});assert.equal(s.refunds[0].total,2034);assert.equal(s.products[0].stock,23);s=apply(s,'refund',{orderId:s.orders[0].id,reason:'Return',items:[{productId:'sample-1',qty:1,restock:false}]});assert.equal(s.orders[0].status,'refunded');assert.equal(expectedCash(s,s.shifts[0]),10000);assert.throws(()=>apply(s,'refund',{orderId:s.orders[0].id,reason:'Again',items:[{productId:'sample-1',qty:1}]}),/refundable/);});
test('fractional-cent tax refunds add back to exactly original tax',()=>{let s=setup();s.products[0].price=1;s=order(s,{items:[{productId:'sample-1',qty:5}]});const original=s.orders[0].tax;for(let i=0;i<5;i++)s=apply(s,'refund',{orderId:s.orders[0].id,reason:'Return',items:[{productId:'sample-1',qty:1,restock:false}]});assert.equal(s.refunds.reduce((n,r)=>n+r.tax,0),original);});
test('unpaid kitchen order consumes once, kitchen transitions do not consume twice',()=>{let s=order(setup(),{mode:'restaurant',items:[{productId:'sample-7',qty:1}],tender:'unpaid'});assert.equal(s.orders[0].status,'unpaid');assert.equal(s.products[6].stock,29);assert.equal(report(s,'2026-09-10','2026-09-10').net,0);s=apply(s,'kitchen',{orderId:s.orders[0].id,status:'preparing'});assert.equal(s.products[6].stock,29);assert.throws(()=>apply(s,'kitchen',{orderId:s.orders[0].id,status:'served'}),/status/);s=apply(s,'pay',{orderId:s.orders[0].id,cashReceived:2000});assert.equal(s.products[6].stock,29);assert.equal(report(s,'2026-09-10','2026-09-10').net,1450);});
test('cancel restores unprepared portions but not prepared food',()=>{const s=order(setup(),{mode:'restaurant',items:[{productId:'sample-7',qty:1}],tender:'unpaid'});const a=apply(s,'cancel',{orderId:s.orders[0].id,reason:'Changed mind'});assert.equal(a.products[6].stock,30);const b=apply(apply(s,'kitchen',{orderId:s.orders[0].id,status:'preparing'}),'cancel',{orderId:s.orders[0].id,reason:'Cancelled'});assert.equal(b.products[6].stock,29);});
test('night business date uses store timezone; DST calendar remains correct',()=>{const settings=emptyStore().settings;assert.equal(businessDate('2026-09-11T06:00:00Z',settings),'2026-09-10');assert.equal(businessDate('2026-09-11T08:00:00Z',settings),'2026-09-11');assert.equal(businessDate('2026-11-01T06:30:00Z',settings),'2026-10-31');assert.equal(businessDate('2026-03-08T07:30:00Z',settings),'2026-03-07');});
test('overnight hours attribute closed day to opening date',()=>{const s={...emptyStore().settings,open:'17:00',close:'02:00',closedDays:[1]};assert.equal(isOpen('2026-09-11T05:00:00Z',s),true);assert.equal(isOpen('2026-09-08T05:00:00Z',s),false);assert.equal(isOpen('2026-09-11T06:00:00Z',s),false);});
test('shift close blocks unpaid checks and preserves immutable cash snapshot',()=>{let s=order(setup(),{mode:'restaurant',items:[{productId:'sample-7',qty:1}],tender:'unpaid'});assert.throws(()=>apply(s,'closeShift',{counted:10000}),/unpaid/);s=apply(s,'pay',{orderId:s.orders[0].id,cashReceived:2000});s=apply(s,'closeShift',{counted:11639});assert.equal(s.shifts[0].expected,11639);assert.equal(s.shifts[0].variance,0);assert.throws(()=>order(s),/shift/);});
test('later refund appears on refund business date',()=>{let s=order(setup());s=apply(s,'refund',{orderId:s.orders[0].id,reason:'Return',items:[{productId:'sample-1',qty:1,restock:false}]},'2026-09-12T16:00:00Z');assert.equal(report(s,'2026-09-10','2026-09-10').net,3600);assert.equal(report(s,'2026-09-12','2026-09-12').net,-1800);});
test('phone acceptance rejects closed hours and requires confirmation',()=>{const s=setup();assert.throws(()=>apply(s,'order',{mode:'restaurant',items:[{productId:'sample-7',qty:1}],channel:'phone',confirmed:true,tender:'unpaid'},'2026-09-10T07:00:00Z'),/closed/);assert.throws(()=>order(s,{confirmed:false}),/Confirm/);});
test('duplicate order lines, negative money and fractional stock rejected',()=>{const s=setup();assert.throws(()=>order(s,{items:[{productId:'sample-1',qty:1},{productId:'sample-1',qty:1}]}),/Duplicate/);assert.throws(()=>order(s,{cashReceived:-1}),/cash/);assert.throws(()=>apply(s,'stock',{productId:'sample-1',count:1.5,reason:'Bad count'}),/stock/);});
test('inventory intake rejects partial interpretation, duplicates and unknown SKUs',()=>{const s=setup();assert.deepEqual(parseInventoryText('RET-001 10\nRET-002,5',s.products),[{sku:'RET-001',qty:10},{sku:'RET-002',qty:5}]);assert.throws(()=>parseInventoryText('RET-001 10\nThis is unclear',s.products));assert.throws(()=>parseInventoryText('RET-001 10\nRET-001 3',s.products));assert.throws(()=>parseInventoryText('UNKNOWN 5',s.products));});
test('receiving import rolls back all rows on invalid item',()=>{const s=setup(),before=structuredClone(s);assert.throws(()=>apply(s,'receive',{rows:[{sku:'RET-001',qty:5},{sku:'NO',qty:1}]}));assert.deepEqual(s,before);});
test('text phone intake matches exact names and rejects invented items',()=>{const s=setup();assert.deepEqual(parseOrderText('2 Classic burger\n1 French fries',s.products),[{productId:'sample-7',qty:2},{productId:'sample-10',qty:1}]);assert.throws(()=>parseOrderText('1 gluten-free burger',s.products),/Unknown/);assert.throws(()=>parseOrderText('999 Classic burger',s.products),/quantity/);});
test('CSV neutralizes formula injection and escapes quotes',()=>{assert.equal(csvCell('=cmd()'),'"\'=cmd()"');assert.equal(csvCell('A"B'),'"A""B"');});
