import {test} from 'node:test';
import assert from 'node:assert/strict';
import {applyOperation,emptyStore,type Store} from '../lib/engine.ts';
import {quoteOrder,signQuote,verifyQuote,validateQuoteAtCommit} from '../lib/voice.ts';
const at='2026-09-10T16:00:00Z',now=Date.parse(at),secret='0123456789abcdef0123456789abcdef';
function setup(){const s=applyOperation(emptyStore(),{id:'seed',type:'seed'},at).state;return applyOperation(s,{id:'shift',type:'openShift',float:0},at).state;}
const draft={callId:'call-123',customer:'Pickup customer',items:[{productId:'sample-7',qty:1}],notes:''};
test('voice quote is signed, owner bound, time bound, and rejects tampering',async()=>{const q=quoteOrder(setup(),'owner',draft,now),token=await signQuote(q,secret);assert.equal((await verifyQuote(token,secret,'owner',now)).total,1639);await assert.rejects(verifyQuote(token,secret,'other',now),/expired/);await assert.rejects(verifyQuote(token,secret,'owner',now+121000),/expired/);await assert.rejects(verifyQuote('X'+token.slice(1),secret,'owner',now));});
test('voice confirmation preserves one order and kitchen job under retries',()=>{const s=setup(),q=quoteOrder(s,'owner',draft,now);const accepted=validateQuoteAtCommit(s,q,now).state;assert.equal(accepted.orders[0].status,'unpaid');assert.equal(accepted.orders[0].kitchen,'new');assert.equal(accepted.prints.length,1);assert.equal(validateQuoteAtCommit(accepted,q,now).duplicate,true);assert.throws(()=>quoteOrder(accepted,'owner',draft,now),/already exists/);});
test('voice must requote changed prices and reject risky dietary requests',()=>{const s=setup(),q=quoteOrder(s,'owner',draft,now);s.products[6].price++;assert.throws(()=>validateQuoteAtCommit(s,q,now),/Price changed/);assert.throws(()=>quoteOrder(s,'owner',{...draft,notes:'Severe peanut allergy'},now),/Staff review/);});
test('printer claim has one owner; transport status never asserts printed paper',()=>{let s=setup();s=applyOperation(s,{id:'sale',type:'order',mode:'retail',items:[{productId:'sample-1',qty:1}],confirmed:true,tender:'cash',cashReceived:10000},at).state;const jobId=s.prints[0].id;s=applyOperation(s,{id:'claim',type:'printClaim',jobId},at).state;assert.equal(s.prints[0].status,'claimed');assert.throws(()=>applyOperation(s,{id:'other-claim',type:'printClaim',jobId},at),/claimed/);assert.throws(()=>applyOperation(s,{id:'ack',type:'printResult',jobId,claimId:'wrong',status:'submitted'},at),/claim/);s=applyOperation(s,{id:'ack',type:'printResult',jobId,claimId:'claim',status:'submitted'},at).state;assert.equal(s.prints[0].status,'submitted');assert.equal(s.prints[0].confirmedAt,undefined);});
