import { test } from 'node:test';
import assert from 'node:assert/strict';
import { applyOperation, emptyStore, type Store } from '../lib/engine.ts';
import { canonical } from '../lib/pos-operations.ts';
import { quoteOrder, signQuote, verifyQuote, validateQuoteAtCommit } from '../lib/voice.ts';
import { readJson, apiFailure } from '../lib/http.ts';
const at = '2026-09-10T16:00:00Z', now = Date.parse(at), secret = '0123456789abcdef0123456789abcdef';
function setup() { return applyOperation(applyOperation(emptyStore(), { id: 'seed', type: 'seed' }, at).state, { id: 'shift', type: 'openShift', float: 0 }, at).state; }
function act(s: Store, op: Record<string, unknown>) { return applyOperation(s, { id: crypto.randomUUID(), ...op } as Parameters<typeof applyOperation>[1], at).state; }
const restaurant = { type: 'order', mode: 'restaurant', tender: 'unpaid', confirmed: true, items: [{ productId: 'sample-7', qty: 1, note: 'No onions' }] };

test('case-insensitive repeated SKU import rejects atomically', () => { const s = setup(); assert.throws(() => act(s, { type: 'receive', rows: [{ sku: 'RET-001', qty: 2 }, { sku: 'ret-001', qty: 3 }] }), /Duplicate/); assert.equal(s.products[0].stock, 24); });
test('canonical idempotency survives JSON key order and older serialized fingerprints', () => { const s = setup(); const op = { id: 'stable', type: 'stock', productId: 'sample-1', count: 20, reason: 'Count' }; const done = applyOperation(s, op, at); done.state.applied.stable.fingerprint = JSON.stringify(op); const reordered = { reason: 'Count', count: 20, productId: 'sample-1', type: 'stock', id: 'stable' }; assert.equal(applyOperation(done.state, reordered, at).duplicate, true); assert.equal(canonical(op), canonical(reordered)); });
test('prototype operation IDs are rejected', () => { for (const id of ['__proto__', 'constructor', 'prototype']) assert.throws(() => applyOperation(setup(), { id, type: 'seed' }, at), /Invalid operation ID/); });
test('held cart does not reserve stock, survives state serialization and can be sold only once', () => { let s = act(setup(), { id: 'held', type: 'hold', mode: 'retail', name: 'Customer', items: [{ productId: 'sample-1', qty: 2 }], notes: '' }); assert.equal(s.products[0].stock, 24); s = JSON.parse(JSON.stringify(s)); const sale = { type: 'order', mode: 'retail', holdId: 'held', confirmed: true, tender: 'cash', cashReceived: 10000, items: [{ productId: 'sample-1', qty: 2 }] }; s = act(s, sale); assert.equal(s.holds?.length, 0); assert.equal(s.products[0].stock, 22); assert.throws(() => act(s, sale), /already completed/); });
test('failed held cart checkout preserves the held cart and stock', () => { const s = act(setup(), { id: 'held', type: 'hold', mode: 'retail', name: 'Customer', items: [{ productId: 'sample-1', qty: 2 }], notes: '' }); assert.throws(() => act(s, { type: 'order', mode: 'retail', holdId: 'held', confirmed: true, tender: 'cash', cashReceived: 0, items: [{ productId: 'sample-1', qty: 2 }] }), /less than/); assert.equal(s.holds?.length, 1); assert.equal(s.products[0].stock, 24); });
test('a table can have only one unpaid check and becomes available after payment', () => { let s = act(setup(), { ...restaurant, id: 'one', tableId: 'table-1' }); assert.throws(() => act(s, { ...restaurant, tableId: 'table-1' }), /already has/); s = act(s, { type: 'pay', orderId: 'one', cashReceived: 5000 }); s = act(s, { ...restaurant, tableId: 'table-1' }); assert.equal(s.orders.length, 2); assert.throws(() => act(s, { ...restaurant, tableId: 'nonexistent' }), /Table not found/); });
test('an addition prints only new items, preserves first ticket, and rejects stale check versions', () => { let s = act(setup(), { ...restaurant, id: 'one' }); const first = structuredClone(s.prints[0].snapshot); s = act(s, { type: 'appendOrder', orderId: 'one', expectedVersion: 1, confirmed: true, expectedTotal: 622, items: [{ productId: 'sample-10', qty: 1, note: 'Extra crispy' }] }); assert.deepEqual(s.prints[0].snapshot, first); assert.equal(s.prints[1].event, 'addition'); assert.equal(s.prints[1].snapshot?.lines.length, 1); assert.equal(s.prints[1].snapshot?.lines[0].name, 'French fries'); assert.equal(s.orders[0].total, 2261); assert.throws(() => act(s, { type: 'appendOrder', orderId: 'one', expectedVersion: 1, confirmed: true, expectedTotal: 622, items: [{ productId: 'sample-10', qty: 1 }] }), /Check changed/); });
test('repriced additions roll back quantity, inventory and ticket changes', () => { const s = act(setup(), { ...restaurant, id: 'one' }); const before = JSON.stringify(s); assert.throws(() => act(s, { type: 'appendOrder', orderId: 'one', expectedVersion: 1, confirmed: true, expectedTotal: 1, items: [{ productId: 'sample-10', qty: 1 }] }), /Price changed/); assert.equal(JSON.stringify(s), before); });
test('cancellation after preparation and additions never restores consumed food', () => { let s = act(setup(), { ...restaurant, id: 'one' }); s = act(s, { type: 'kitchen', orderId: 'one', status: 'preparing' }); s = act(s, { type: 'appendOrder', orderId: 'one', expectedVersion: 1, expectedTotal: 622, confirmed: true, items: [{ productId: 'sample-10', qty: 1 }] }); s = act(s, { type: 'cancel', orderId: 'one', reason: 'Customer left' }); assert.equal(s.products[6].stock, 29); assert.equal(s.products[9].stock, 39); assert.equal(s.prints.at(-1)?.event, 'cancellation'); s = act(s, { type: 'printClaim', jobId: s.prints.at(-1)!.id }); assert.equal(s.prints.at(-1)?.status, 'claimed'); assert.throws(() => act(s, { type: 'printClaim', jobId: s.prints[0].id }), /closed/); });
test('product edits preserve historical amounts and enforce SKU uniqueness', () => { let s = act(setup(), { ...restaurant, id: 'one' }); const op = { type: 'editProduct', productId: 'sample-7', sku: 'FOOD-001', name: 'Renamed burger', category: 'Main', price: 1800, cost: 500, low: 4, taxBps: 1300 }; s = act(s, op); assert.equal(s.orders[0].total, 1639); assert.equal(s.orders[0].lines[0].name, 'Classic burger'); assert.equal(s.products[6].price, 1800); assert.throws(() => act(s, { ...op, sku: 'ret-001' }), /SKU already/); });
test('expired voice confirmation recovers only an exact already accepted request', async () => { const q = quoteOrder(setup(), 'owner', { callId: 'call', customer: 'Pat', items: [{ productId: 'sample-7', qty: 1 }], notes: '' }, now); const token = await signQuote(q, secret), accepted = validateQuoteAtCommit(setup(), q, now).state; await assert.rejects(verifyQuote(token, secret, 'owner', now + 121000, setup()), /expired/); assert.equal((await verifyQuote(token, secret, 'owner', now + 121000, accepted)).id, q.id); assert.equal(validateQuoteAtCommit(accepted, q, now + 121000).duplicate, true); });
test('a newer phone quote invalidates an older unaccepted quote', () => { let s = setup(); const q = quoteOrder(s, 'owner', { callId: 'call', customer: 'Pat', items: [{ productId: 'sample-7', qty: 1 }], notes: '' }, now); q.operation.quoteId = q.id; s = act(s, { type: 'voiceDraft', callId: 'call', quoteId: 'replacement' }); assert.throws(() => validateQuoteAtCommit(s, q, now), /replaced/); s = act(s, { type: 'voiceDraft', callId: 'call', quoteId: q.id }); assert.equal(validateQuoteAtCommit(s, q, now).state.orders.length, 1); });
test('reprints are explicit copies with separate jobs; manual claims identify delivery owner', () => { let s = act(setup(), { ...restaurant, id: 'one' }); const jobId = s.prints[0].id; assert.throws(() => act(s, { type: 'reprint', jobId, reason: 'Copy' }), /Resolve/); s = act(s, { type: 'printClaim', jobId, delivery: 'manual' }); assert.equal(s.prints[0].delivery, 'manual'); s = act(s, { type: 'printConfirm', jobId }); s = act(s, { type: 'reprint', jobId, reason: 'Lost original' }); assert.equal(s.prints[1].event, 'reprint'); assert.notEqual(s.prints[0].id, s.prints[1].id); });
test('streamed request limits count bytes and cancel oversized requests', async () => { const req = new Request('https://example.test', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ text: 'é'.repeat(30) }) }); await assert.rejects(readJson(req, 45), /too large/); const valid = new Request('https://example.test', { method: 'POST', headers: { 'content-type': 'application/json' }, body: '{"id":"1"}' }); assert.deepEqual(await readJson(valid), { id: '1' }); });
test('database contention maps to retryable 503', () => { assert.equal(apiFailure(new Error('Another register is updating. Please retry this action.')).status, 503); });
test('new additions have separate kitchen batches without restarting earlier preparation', () => { let s = act(setup(), { ...restaurant, id: 'one' }); s = act(s, { type: 'kitchen', orderId: 'one', batchId: 'one', status: 'preparing' }); s = act(s, { id: 'added', type: 'appendOrder', orderId: 'one', expectedVersion: 1, confirmed: true, expectedTotal: 622, items: [{ productId: 'sample-10', qty: 1 }] }); assert.equal(s.orders[0].batches?.[0].status, 'preparing'); assert.equal(s.orders[0].batches?.[1].status, 'new'); s = act(s, { type: 'kitchen', orderId: 'one', batchId: 'one', status: 'ready' }); assert.equal(s.orders[0].batches?.[0].status, 'ready'); assert.equal(s.orders[0].batches?.[1].status, 'new'); assert.equal(s.orders[0].kitchen, 'new'); });
test('unresolved printer claims can be reconciled without falsely confirming paper', () => { let s = act(setup(), { ...restaurant, id: 'one' }); const jobId = s.prints[0].id; assert.throws(() => act(s, { type: 'printConfirm', jobId }), /Reserve/); s = act(s, { type: 'printClaim', jobId }); assert.throws(() => act(s, { type: 'printReconcile', jobId, reason: 'Printer restarted' }), /Stop/); s = act(s, { type: 'printReconcile', jobId, reason: 'Worker stopped; output unknown', bridgeStopped: true }); assert.equal(s.prints[0].status, 'uncertain'); assert.equal(s.prints[0].confirmedAt, undefined); });
test('a full restaurant refund queues a cancellation for the kitchen', () => { let s = act(setup(), { ...restaurant, id: 'one', tender: 'cash', cashReceived: 5000 }); s = act(s, { type: 'refund', orderId: 'one', reason: 'Customer cancelled', items: [{ productId: 'sample-7', qty: 1, restock: false }] }); assert.equal(s.orders[0].kitchen, 'cancelled'); assert.equal(s.prints.at(-1)?.event, 'cancellation'); });
