'use client';
import {useEffect,useState} from 'react';
import {Globe2,ArrowRight} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {channelNames,type Channel} from '@/lib/channels';
import {money,type Store,type Operation,type Mode} from '@/lib/engine';
export default function ChannelInbox({state,run,disabled,mode}:{state:Store;run:(op:Omit<Operation,'id'>)=>Promise<boolean>;disabled:boolean;mode:Mode}){
 const [source,setSource]=useState('all'),[selectedId,setSelectedId]=useState(''),[confirmed,setConfirmed]=useState(false),[handled,setHandled]=useState(false),[reason,setReason]=useState('');
 const [now,setNow]=useState(()=>Date.now());
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),15000);return()=>clearInterval(timer);},[]);
 const [prep,setPrep]=useState(String(state.online?.prepMinutes??20));
 const requests=(state.channelRequests??[]).filter(r=>r.mode===mode&&(source==='all'||r.source===source));
 const selected=state.channelRequests?.find(r=>r.id===selectedId);
 return <section className="pos-section"><div className="pos-section-heading"><div><h2>Online & delivery orders</h2><p>Review incoming requests before stock is committed and tickets are sent.</p></div><a className="pos-link-button" href={'/order/'+mode} target="_blank" rel="noreferrer">Open ordering page<ArrowRight size={16}/></a></div>
  <div className="channel-connections">{(Object.keys(channelNames) as Channel[]).map(c=><article key={c}><Globe2 size={21}/><h3>{channelNames[c]}</h3><strong>{c==='online'?(state.online?.enabled?'Requests enabled':'Paused'):'Not connected'}</strong><p>{c==='online'?'Pickup requests, paid at collection. Current hosted access stays private.':'Requires approved access or an authorized integration partner. No live connection is claimed.'}</p></article>)}</div>
  <div className="channel-settings"><label className="pos-field"><span>Pickup estimate (minutes)</span><input type="number" min="5" max="180" value={prep} onChange={e=>setPrep(e.target.value)}/></label><Button disabled={disabled||!Number.isInteger(Number(prep))||Number(prep)<5||Number(prep)>180} onClick={()=>void run({type:'onlineSettings',enabled:!state.online?.enabled,prepMinutes:Number(prep)})}>{state.online?.enabled?'Pause online pickup':'Enable online pickup'}</Button><p>Applies to both registers. Store hours and an open cash shift are also required.</p></div>
  <label className="pos-field channel-filter"><span>Order channel</span><select value={source} onChange={e=>setSource(e.target.value)}><option value="all">All channels</option>{(Object.keys(channelNames) as Channel[]).map(c=><option key={c} value={c}>{channelNames[c]}</option>)}</select></label>
  <div className="pos-order-grid">{[...requests].reverse().map(r=><button className="pos-order-card clickable" key={r.id} onClick={()=>{setSelectedId(r.id);setConfirmed(false);setHandled(false);setReason('');}}><div><b>{channelNames[r.source]}</b><span>{r.status==='pending'?(r.source==='online'&&now-Date.parse(r.createdAt)>30*60*1000?'Expired':'Needs review'):r.status}</span></div><h3>{r.customer}</h3><p>{r.externalId}</p><p>{r.items.reduce((n,l)=>n+l.qty,0)} items · {r.fulfillment}</p><div><strong>{money(r.total)}</strong><span>{r.payment==='platform_collected'?'Platform collected':'Pay at pickup'}</span></div></button>)}</div>
  {!requests.length&&<div className="pos-empty"><Globe2/><h3>No requests yet</h3><p>Online pickup requests will appear here. Marketplace orders require a connected, approved bridge.</p></div>}
  <Dialog open={!!selected} onOpenChange={v=>{if(!v)setSelectedId('');}}><DialogContent className="pos-dialog"><DialogHeader><DialogTitle>{selected?channelNames[selected.source]:'Order'} request</DialogTitle><DialogDescription>Pending requests do not reserve stock. Accepting checks current stock and prices again.</DialogDescription></DialogHeader>{selected&&<><h3>{selected.customer}</h3><p>{selected.externalId} · {selected.status}</p><div className="pos-review-lines">{selected.items.map(l=><p key={l.productId}><b>{l.qty}× {l.name}</b><span>{money(l.qty*l.price)}</span>{l.note&&<small>{l.note}</small>}</p>)}</div>{selected.notes&&<p>{selected.notes}</p>}<div className="pos-change">Total<strong>{money(selected.total)}</strong></div><p>{selected.payment==='platform_collected'?'Payment was collected by the platform. Do not collect cash again. Jawa does not verify the provider payout.':'Payment is due at collection. This request has not charged a card.'}</p>
   {selected.status==='pending'&&<>{selected.source!=='online'&&<label className="pos-check"><input type="checkbox" checked={handled} onChange={e=>setHandled(e.target.checked)}/>I checked this order and payment on the platform. Any decline has already been handled there.</label>}<label className="pos-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Items, instructions and amount are correct.</label><Button disabled={disabled||!confirmed||(selected.source!=='online'&&!handled)} onClick={async()=>{if(await run({type:'channelAccept',requestId:selected.id,confirmed,platformHandled:handled}))setSelectedId('');}}>Accept into POS {mode==='restaurant'?'& send to kitchen':''}</Button><label className="pos-field"><span>Reason if declining</span><input maxLength={200} value={reason} onChange={e=>setReason(e.target.value)}/></label><Button variant="outline" disabled={disabled||!reason.trim()||(selected.source!=='online'&&!handled)} onClick={async()=>{if(await run({type:'channelReject',requestId:selected.id,reason,platformHandled:handled}))setSelectedId('');}}>Decline locally</Button><p className="pos-help">Local actions do not update DoorDash, Uber Eats or Skip. Provider status, cancellations and refunds must be handled there until the connector is activated.</p></>}
   {selected.reason&&<p>{selected.reason}</p>}
  </>}</DialogContent></Dialog>
 </section>;
}
