'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {ShoppingBag,Minus,Plus,ArrowLeft,RefreshCw} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {money,type Mode} from '@/lib/engine';
import {newId} from '@/lib/ids';
import type {onlineMenu} from '@/lib/channels';
type Menu=ReturnType<typeof onlineMenu>&{privatePreview:boolean;storeKey:string};
type Receipt={requestId:string;status:string;reason?:string;orderNumber?:number;orderStatus?:string;kitchen?:string;total:number;payment:string};
type RequestDraft={id:string;receiptKey:string;action:'submit';mode:Mode;customer:string;notes:string;items:{productId:string;qty:number}[];expectedTotal:number;confirmed:true};
export default function OnlineOrder({mode}:{mode:Mode}){
 const [menu,setMenu]=useState<Menu|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState('');
 const [cart,setCart]=useState<Record<string,number>>({}),[name,setName]=useState(''),[notes,setNotes]=useState(''),[confirmed,setConfirmed]=useState(false);
 const [draft,setDraft]=useState<RequestDraft|null>(null),[receipt,setReceipt]=useState<Receipt|null>(null);
 const locked=useRef(false),key=menu?'jawa-online-request-v1:'+menu.storeKey+':'+mode:'';
 const load=useCallback(async()=>{try{const res=await fetch('/api/online',{cache:'no-store'});const data=await res.json() as Menu&{error?:string};if(!res.ok)throw new Error(data.error||'The menu could not be loaded.');setMenu(data);setConfirmed(false);setError('');}catch(e){setError(e instanceof Error?e.message:'Connection unavailable.');}},[]);
 useEffect(()=>{const controller=new AbortController();void fetch('/api/online',{cache:'no-store',signal:controller.signal}).then(async res=>{const data=await res.json() as Menu&{error?:string};if(!res.ok)throw new Error(data.error||'The menu could not be loaded.');setMenu(data);const storageKey='jawa-online-request-v1:'+data.storeKey+':'+mode;setDraft(null);setReceipt(null);setCart({});setConfirmed(false);try{const stored=sessionStorage.getItem(storageKey);if(stored)setDraft(JSON.parse(stored));}catch{setError('Enable browser session storage to recover interrupted requests.');}}).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Connection unavailable.');});return()=>controller.abort();},[mode]);
 const checkStatus=useCallback(async(d:RequestDraft)=>{try{const res=await fetch('/api/online',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'status',requestId:d.id,receiptKey:d.receiptKey})});const data=await res.json() as Receipt&{error?:string};if(res.ok){setReceipt(data);setError('');}else if(res.status!==404)throw new Error(data.error||'Status unavailable.');}catch(e){setError(e instanceof Error?e.message:'Status unavailable.');}},[]);
 useEffect(()=>{if(!draft)return;const controller=new AbortController();void fetch('/api/online',{method:'POST',signal:controller.signal,headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'status',requestId:draft.id,receiptKey:draft.receiptKey})}).then(async res=>{const data=await res.json() as Receipt&{error?:string};if(res.ok){setReceipt(data);setError('');}else if(res.status!==404)throw new Error(data.error||'Status unavailable.');}).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Status unavailable.');});const id=setInterval(()=>void checkStatus(draft),10000);return()=>{controller.abort();clearInterval(id);};},[draft,checkStatus]);
 const products=(menu?.products??[]).filter(p=>p.mode===mode),lines=products.filter(p=>cart[p.id]).map(p=>({...p,qty:cart[p.id]}));
 const total=lines.reduce((n,l)=>n+l.price*l.qty+Math.round(l.price*l.qty*l.taxBps/10000),0);
 const add=(id:string,delta:number)=>{setCart(old=>({...old,[id]:Math.max(0,Math.min(99,(old[id]??0)+delta))}));setConfirmed(false);};
 const submit=async()=>{
  if(locked.current)return;locked.current=true;setBusy(true);setError('');
  const data=draft??{id:newId(),receiptKey:(newId()+newId()).replaceAll('-',''),action:'submit' as const,mode,customer:name,notes,items:lines.map(l=>({productId:l.id,qty:l.qty})),expectedTotal:total,confirmed:true as const};
  try{
   sessionStorage.setItem(key,JSON.stringify(data));setDraft(data);
   const res=await fetch('/api/online',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await res.json() as Receipt&{error?:string};
   if(!res.ok){if(res.status>=400&&res.status<500&&![408,429].includes(res.status)){sessionStorage.removeItem(key);setDraft(null);}throw new Error(result.error||'The result is unknown. Recover this request before starting another.');}
   setReceipt(result);setCart({});
  }catch(e){setError(e instanceof Error?e.message:'Connection interrupted. Recover the same request.');}
  finally{locked.current=false;setBusy(false);}
 };
 return <main className="online-shop"><header><a href="/" className="online-logo">j. <strong>jawa</strong></a><div><h1>{menu?.store??'Online ordering'}</h1><p>{mode==='restaurant'?'Order food for pickup':'Shop for store pickup'}</p></div><a href={'/order/'+(mode==='restaurant'?'retail':'restaurant')}>Switch to {mode==='restaurant'?'store':'restaurant'}</a></header>
  <div className="online-notice">Pickup only · Pay at collection · Requests need store acceptance. No online card charge.</div>
  {menu?.privatePreview&&<p className="online-notice">Private owner preview. This page currently uses your own signed-in store; public merchant ordering needs configuration.</p>}
  {error&&<div className="pos-alert" role="alert">{error}<Button variant="outline" onClick={()=>void load()} disabled={busy}>Refresh menu</Button></div>}
  {receipt?<section className="online-receipt" aria-live="polite"><ShoppingBag size={36}/><h2>{receipt.orderStatus==='cancelled'?'Order cancelled':receipt.status==='pending'?'Request sent — waiting for the store':receipt.status==='accepted'?'Order accepted':receipt.status==='expired'?'Request expired':'Request declined'}</h2><p>{receipt.orderNumber?'Order #'+receipt.orderNumber:'Reference '+receipt.requestId}</p>{receipt.reason&&<p>{receipt.reason}</p>}<strong>{money(receipt.total)}</strong><p>{['rejected','expired'].includes(receipt.status)||receipt.orderStatus==='cancelled'?'This page did not take an online payment.':receipt.payment==='paid'?'Payment recorded by the store':'Pay when you collect your order.'}</p>{receipt.kitchen&&receipt.kitchen!=='none'&&<p>Preparation: {receipt.kitchen}</p>}{receipt.orderStatus==='refunded'&&<p>The store recorded a full refund for this order.</p>}{receipt.orderStatus==='cancelled'&&<p>The store cancelled this order. Do not travel to collect it.</p>}<p>Keep this page open for updates. Contact the store directly about changes or dietary requirements.</p><Button variant="outline" onClick={()=>draft&&void checkStatus(draft)}><RefreshCw size={16}/>Check status</Button>{(['rejected','expired'].includes(receipt.status)||['cancelled','refunded'].includes(receipt.orderStatus??'')||(receipt.payment==='paid'&&(mode==='retail'||receipt.kitchen==='served')))&&<Button onClick={()=>{sessionStorage.removeItem(key);setDraft(null);setReceipt(null);setConfirmed(false);void load();}}>Start a new request</Button>}</section>:draft?<section className="online-receipt"><h2>Recover your request</h2><p>Its outcome may already be saved. Recover using the same reference to avoid a duplicate.</p><Button disabled={busy} onClick={()=>void submit()}>{busy?'Checking…':'Recover same request'}</Button></section>:!menu?<section className="online-receipt"><h2>{error?'Ordering is unavailable':'Loading the menu'}</h2><p>{error?'Please try again later.':'Please wait while current items are loaded.'}</p></section>:<>
   <div className="online-hours"><Button variant="outline" onClick={()=>void load()} disabled={busy}>Refresh availability</Button><strong>{menu.open?'Taking pickup requests':'Currently closed or paused'}</strong><span>{menu.hours.open}–{menu.hours.close} · {menu.timezone} · Estimate {menu.prepMinutes} minutes after acceptance</span></div>
   <div className="online-columns"><section><label className="pos-field"><span>Search {mode==='restaurant'?'menu':'products'}</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by item name"/></label><div className="online-products">{products.filter(p=>(p.name+' '+p.category).toLowerCase().includes(search.toLowerCase())).map(p=><article key={p.id}><span>{p.category}</span><h2>{p.name}</h2><strong>{money(p.price)}</strong><small>Before configured tax</small><Button variant="outline" disabled={!p.available||!menu.open||busy} onClick={()=>add(p.id,1)}>{p.available?'Add to order':'Unavailable'}<Plus size={16}/></Button></article>)}</div>{!products.length&&<p>No items have been added yet.</p>}</section>
   <aside className="online-cart"><h2>Your pickup order</h2>{lines.map(l=><div className="online-cart-line" key={l.id}><strong>{l.name}</strong><span>{money(l.price*l.qty)}</span><div><Button variant="outline" aria-label={'Remove one '+l.name} onClick={()=>add(l.id,-1)}><Minus size={15}/></Button><b>{l.qty}</b><Button variant="outline" aria-label={'Add one '+l.name} onClick={()=>add(l.id,1)}><Plus size={15}/></Button></div></div>)}{!lines.length&&<p>Add items to get started.</p>}<label className="pos-field"><span>Pickup name</span><input value={name} maxLength={80} onChange={e=>{setName(e.target.value);setConfirmed(false);}}/></label><label className="pos-field"><span>Instructions (optional)</span><textarea value={notes} maxLength={500} onChange={e=>{setNotes(e.target.value);setConfirmed(false);}}/></label><p>Contact staff directly about allergies. Availability is confirmed when the store accepts.</p><div className="pos-change">Total with configured tax<strong>{money(total)}</strong></div><label className="pos-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I checked the items, total and pickup details.</label><Button disabled={busy||!menu.open||!confirmed||!name.trim()||!lines.length} onClick={()=>void submit()}>{busy?'Sending…':'Request pickup order'}</Button></aside></div></>}
 </main>;
}
