import {useEffect,useState} from 'react';
type Row={id:string;number:number;business_date:string;mode:string;status:string;channel:string;total:number};
type Receipt={order:{number:number;reference:string;createdAt:string;status:string;total:number;tax:number;lines:{productId:string;name:string;qty:number;price:number;refunded:number;note?:string}[]};refunds:{id:string;at:string;reason:string;total:number}[];versions:number};
const money=(v:number)=>new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(v/100);
export default function History(){
 const [filters,setFilters]=useState({from:'',to:'',mode:'all',status:'all',number:''}),[rows,setRows]=useState<Row[]>([]),[next,setNext]=useState<number|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[receipt,setReceipt]=useState<Receipt|null>(null),[loaded,setLoaded]=useState(false),[page,setPage]=useState(1);
 const load=async(before?:number)=>{setBusy(true);setError('');setReceipt(null);setRows([]);setNext(null);setLoaded(false);try{const params=new URLSearchParams();for(const [k,v]of Object.entries(filters))if(v)params.set(k,v);if(before)params.set('before',String(before));const r=await fetch('/api/admin/history?'+params);const data=await r.json() as {orders:Row[];nextBefore:number|null;error?:string};if(!r.ok)throw new Error(data.error||'History unavailable.');setRows(data.orders);setNext(data.nextBefore);setLoaded(true);setPage(n=>before?n+1:1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 useEffect(()=>{const controller=new AbortController();void fetch('/api/admin/history?mode=all',{signal:controller.signal}).then(async r=>{const data=await r.json() as {orders:Row[];nextBefore:number|null;error?:string};if(!r.ok)throw new Error(data.error||'History unavailable.');setRows(data.orders);setNext(data.nextBefore);setLoaded(true);}).catch(e=>{if(!controller.signal.aborted)setError((e as Error).message);});return()=>controller.abort();},[]);
 const details=async(id:string)=>{setBusy(true);setError('');setReceipt(null);try{const r=await fetch('/api/admin/history?'+new URLSearchParams({id}));const data=await r.json() as Receipt & {error?:string};if(!r.ok)throw new Error(data.error||'Receipt unavailable.');setReceipt(data);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const update=(key:string,value:string)=>{setFilters(old=>({...old,[key]:value}));setNext(null);};
 const download=()=>{if(!receipt)return;const url=URL.createObjectURL(new Blob([JSON.stringify(receipt,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`jawa-order-${receipt.order.number}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <section className="ops-panel"><div className="ops-panel-title"><h2>Every order has a history</h2><span>Owner access · page {page}</span></div><p>Search the durable journal by order number or creation business date. Revenue reports use payment and refund dates instead.</p><form className="ops-history-filters" onSubmit={e=>{e.preventDefault();void load();}}>
 <label>Order number<input inputMode="numeric" pattern="[1-9][0-9]*" value={filters.number} onChange={e=>update('number',e.target.value)} placeholder="e.g. 1001" disabled={busy}/></label>
 <label>From<input type="date" value={filters.from} onChange={e=>update('from',e.target.value)} disabled={busy}/></label><label>Through<input type="date" min={filters.from} value={filters.to} onChange={e=>update('to',e.target.value)} disabled={busy}/></label>
 <label>Register<select value={filters.mode} onChange={e=>update('mode',e.target.value)} disabled={busy}><option value="all">Both registers</option><option value="restaurant">Restaurant</option><option value="retail">Retail</option></select></label>
 <label>Status<select value={filters.status} onChange={e=>update('status',e.target.value)} disabled={busy}>{['all','paid','unpaid','refunded','cancelled'].map(v=><option value={v} key={v}>{v==='all'?'All statuses':v}</option>)}</select></label><button disabled={busy}>{busy?'Loading…':'Search history'}</button></form>
 {error&&<p role="alert" className="ops-alert">{error}</p>}
 <div className="ops-table-scroll"><table><thead><tr>{['Order','Business date','Register','Channel','Status','Order total','Details'].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>#{r.number}</td><td>{r.business_date}</td><td>{r.mode}</td><td>{r.channel}</td><td>{r.status}</td><td>{money(r.total)}</td><td><button disabled={busy} onClick={()=>void details(r.id)} aria-label={'View order '+r.number}>View</button></td></tr>)}</tbody></table></div>
 {loaded&&!rows.length&&<p>No matching orders. Change the filters and search again.</p>}{next!==null&&<button disabled={busy} onClick={()=>void load(next!)}>Older orders →</button>}{page>1&&<button disabled={busy} onClick={()=>void load()}>Back to newest results</button>}
 {receipt&&<div className="ops-history-receipt"><div className="ops-panel-title"><h2>Order #{receipt.order.number}</h2><button onClick={download}>Download receipt record</button></div><p>{receipt.order.reference||'No customer reference'} · {receipt.order.status} · {receipt.versions} recorded versions</p><ul>{receipt.order.lines.map(l=><li key={l.productId}><b>{l.qty} × {l.name}</b> — {money(l.price)} each · {l.refunded} refunded{l.note&&<small>{l.note}</small>}</li>)}</ul><p><b>Order total before refunds: {money(receipt.order.total)}</b> · included tax {money(receipt.order.tax)}</p><h3>Refund history</h3>{receipt.refunds.length?receipt.refunds.map(r=><p key={r.id}>{new Date(r.at).toLocaleString()} · {money(r.total)} · {r.reason}</p>):<p>No refunds recorded.</p>}<small>The JSON download is a business record, not a payment-provider receipt. Journal entries begin at this upgrade; earlier intermediate versions cannot be reconstructed.</small></div>}
 </section>;
}
