import {useCallback,useEffect,useState,lazy,Suspense} from 'react';
const History=lazy(()=>import('./history'));
import {ArrowUpRight,Check,ChevronRight,ClipboardList,Download,ExternalLink,Headphones,Package,Printer,RefreshCw,ShoppingBag,UtensilsCrossed} from 'lucide-react';
import type {storeOverview} from './overview';
type Overview=ReturnType<typeof storeOverview>&{activity:{scope:string;last_seen:string;method:string}[];maintenanceError:string};
type Daily={day:string;generated_at:string;payload:{net:number;tax:number;cash:number;external:number;count:number}};
const money=(n:number)=>new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(n/100);
export default function Operations(){
 const [data,setData]=useState<Overview|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('overview'),[copied,setCopied]=useState('');
 const [from,setFrom]=useState(''),[to,setTo]=useState(''),[daily,setDaily]=useState<Daily[]>([]),[loadedReports,setLoadedReports]=useState(false);
 const refresh=useCallback(async()=>{setBusy(true);setError('');try{const r=await fetch('/api/admin/overview',{cache:'no-store'});if(!r.ok)throw new Error('Could not load store status. Sign in again or retry.');const value=await r.json() as Overview;setData(value);setFrom(old=>old||value.day);setTo(old=>old||value.day);}catch(e){setError((e as Error).message);}finally{setBusy(false);}},[]);
 useEffect(()=>{const controller=new AbortController();void fetch('/api/admin/overview',{cache:'no-store',signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error('Could not load store status. Sign in again or retry.');const value=await r.json() as Overview;setData(value);setFrom(old=>old||value.day);setTo(old=>old||value.day);}).catch(e=>{if(!controller.signal.aborted)setError((e as Error).message);});return()=>controller.abort();},[]);
 if(!data)return <section className="ops-loading"><h2>Your store, at a glance</h2><p>{error||'Loading your live store records…'}</p>{error&&<button onClick={()=>void refresh()}>Try again</button>}</section>;
 const base='/'+data.mode;
 const checklist=[{title:'Add your catalogue',done:data.storage.products>0,href:'/manage?view=inventory',detail:`${data.storage.products} products saved`},{title:'Review your trading hours',done:false,href:'/manage?view=settings',detail:`${data.hours.open}–${data.hours.close} · ${data.timezone}`},{title:'Open a cash shift',done:data.shiftOpen,href:base+'?screen=cash',detail:data.shiftOpen?'Shift is open':'Opening float required before cash sales'},{title:'Set up online pickup',done:data.integrations[0].configured,href:base+'?screen=online',detail:data.integrations[0].status}];
 const exportCsv=async()=>{setBusy(true);setError('');try{const r=await fetch('/api/admin/report-export?'+new URLSearchParams({from,to}));if(!r.ok)throw new Error((await r.json() as {error:string}).error);const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=`jawa-report-${from}-${to}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const loadReports=async()=>{setBusy(true);setError('');try{const r=await fetch('/api/admin/reports');if(!r.ok)throw new Error('Unable to load daily summaries.');setDaily((await r.json() as {reports:Daily[]}).reports);setLoadedReports(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <div className="ops-console">
  <header className="ops-hero"><div><span className="ops-kicker">JAWA / STORE CONTROL</span><h1>A little less admin.<br/><em>More time for your customers.</em></h1><p>{data.store} <span>·</span> {data.day} <span>·</span> {data.shiftOpen?'Cash shift open':'Cash shift closed'}</p><a className="ops-primary" href={base}>Open {data.mode==='restaurant'?'restaurant':'retail'} register <ArrowUpRight size={18}/></a></div><div className="ops-hero-art" aria-hidden="true"><div className="ops-art-orbit"/><div className="ops-art-ticket"><span>YOUR NEXT GOOD DAY</span><b>jawa.</b><i>Orders. People. Possibilities.</i><div>● ● ● ● ● ● ● ●</div></div></div></header>
  <div className="ops-tabbar"><nav aria-label="Store control sections">{[['overview','Overview'],['connections','Connections'],['reports','Reports'],['history','History']].map(([id,label])=><button key={id} aria-current={tab===id?'page':undefined} className={tab===id?'selected':''} onClick={()=>setTab(id)}>{label}</button>)}<a href="#account-tools">Staff & backups</a></nav><button className="ops-refresh" onClick={()=>void refresh()} disabled={busy}><RefreshCw size={15}/> Refresh</button></div>
  {error&&<p className="ops-alert" role="alert">{error}</p>}{data.maintenanceError&&<p className="ops-alert" role="alert">{data.maintenanceError}</p>}
  {tab==='overview'&&<><div className="ops-metrics">{[['Net sales today',money(data.today.net),'After returns, before tax'],['Paid orders',String(data.today.count),'Current business day'],['Cash collected',money(data.today.cash),'After cash refunds'],['Platform collected',money(data.today.external),'Separate from your drawer']].map(([label,value,note])=><section key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></section>)}</div>
  <div className="ops-two"><section className="ops-panel"><div className="ops-panel-title"><h2>Keep the day moving</h2><span>Refresh for latest</span></div><div className="ops-queues">{[[ClipboardList,'Open orders',data.queues.unpaid,base+'?screen=checks'],[UtensilsCrossed,'Kitchen tickets',data.queues.kitchen,'/restaurant?screen=kitchen'],[ShoppingBag,'Online requests',data.queues.inbox,base+'?screen=online'],[Printer,'Paper to verify',data.queues.printReview,base+'?screen=printers'],[Package,'Low stock items',data.queues.lowStock,'/manage?view=inventory']].map(([Icon,title,count,href])=>{const Glyph=Icon as typeof Package;return <a key={String(title)} href={String(href)}><Glyph size={19}/><span>{String(title)}</span><b>{String(count)}</b><ChevronRight size={16}/></a>;})}</div><p className="ops-note">{data.queues.printPending} print jobs waiting · {data.queues.expired} expired online requests to review</p></section>
  <section className="ops-panel"><div className="ops-panel-title"><h2>Make it your store</h2><span>Setup essentials</span></div>{checklist.map(c=><a className="ops-check" key={c.title} href={c.href}><span className={c.done?'done':''}>{c.done?<Check size={16}/>:<ChevronRight size={16}/>}</span><div><b>{c.title}</b><small>{c.detail}</small></div><ArrowUpRight size={16}/></a>)}<a className="ops-guide" href="/api/admin/deployment-guide"><Download size={17}/> Customer deployment guide (.md)</a></section></div>
  <section className="ops-capacity"><div><b>Installation capacity</b><p>This release has bounded storage. Arrange an upgrade before reaching these limits; exporting a report does not clear records.</p></div><div><label>Orders <b>{data.storage.orders} / {data.storage.orderLimit}</b></label><progress value={data.storage.orders} max={data.storage.orderLimit}/><label>Store data <b>{Math.round(data.storage.bytes/1000)} / {data.storage.byteLimit/1000} KB</b></label><progress value={data.storage.bytes} max={data.storage.byteLimit}/></div></section></>}
  {tab==='connections'&&<><section className="ops-connection-intro"><Headphones size={28}/><div><h2>One place for every order.</h2><p>Check what is configured, open each workflow, and follow the deployment guide to connect your services. Configuration alone does not prove a live connection.</p></div><a href="/api/admin/deployment-guide"><Download size={17}/> Setup guide</a></section><div className="ops-connections">{data.integrations.map(i=>{const activity=data.activity.find(a=>a.scope===(['doordash','ubereats','skip'].includes(i.id)?'channels':i.id));return <section className="ops-panel" key={i.id}><div className="ops-panel-title"><h2>{i.name}</h2><span className={i.id==='online'&&i.status==='Accepting requests'?'ops-badge active':'ops-badge'}>{i.status}</span></div><p>{i.detail}</p>{activity&&<small>Last successful {activity.scope} API request: {new Date(activity.last_seen).toLocaleString()}. This is not a hardware or call test.</small>}{i.id==='online'?<><label className="ops-link-field">Customer pickup page<input readOnly value={data.links[data.mode as 'restaurant'|'retail']}/></label><div className="ops-actions"><a href={data.links[data.mode as 'restaurant'|'retail']} target="_blank" rel="noreferrer">Open page <ExternalLink size={14}/></a><button onClick={async()=>{try{await navigator.clipboard.writeText(data.links[data.mode as 'restaurant'|'retail']);setCopied('Link copied');}catch{setCopied('Select and copy the link above.');}}}>Copy link</button><span role="status">{copied}</span></div><small>Localhost links work on this computer only. Configure your HTTPS domain before sharing with customers.</small></>:null}{['voice','printer'].includes(i.id)&&<a className="ops-inline-link" href={i.id==='voice'?'/restaurant?screen=calls':base+'?screen=printers'}>Open {i.id==='voice'?'phone orders':'print queue'} <ArrowUpRight size={15}/></a>}</section>;})}</div></>}
  {tab==='history'&&<Suspense fallback={<p>Opening transaction history…</p>}><History/></Suspense>}
  {tab==='reports'&&<section className="ops-panel"><div className="ops-panel-title"><h2>Your numbers, your time range</h2><span>{data.timezone} · cutoff {data.cutoff}</span></div><p>Choose inclusive business dates. Cash and platform collections remain separate. These summaries are not payment-provider settlement statements.</p><form className="ops-range" onSubmit={e=>{e.preventDefault();void exportCsv();}}><label>From<input type="date" required value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Through<input type="date" required min={from} value={to} onChange={e=>setTo(e.target.value)}/></label><button disabled={busy}><Download size={17}/> Download CSV</button></form><div className="ops-panel-title"><h2>Closed business days</h2><button disabled={busy} onClick={()=>void loadReports()}>Load summaries</button></div>{daily.length>0?<div className="ops-table-scroll"><table><thead><tr>{['Business date','Orders','Net sales','Net tax','Cash','Platform collected'].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{daily.map(r=><tr key={r.day}><td>{r.day}</td><td>{r.payload.count}</td><td>{money(r.payload.net)}</td><td>{money(r.payload.tax)}</td><td>{money(r.payload.cash)}</td><td>{money(r.payload.external)}</td></tr>)}</tbody></table></div>:<p>{loadedReports?'No closed business-day summaries yet.':'Load summaries to view daily totals here.'}</p>}</section>}
 </div>;
}
