import {readFileSync,writeFileSync,mkdirSync,existsSync,readdirSync,renameSync,unlinkSync} from 'node:fs';
import {resolve} from 'node:path';
import {scryptSync,createDecipheriv} from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
const[source,passphraseFile,target]=process.argv.slice(2);if(!source||!passphraseFile||!target)throw new Error('Usage: node server/restore.mjs BACKUP.jawabak PASSPHRASE_FILE NEW_DATA_DIRECTORY');
const dir=resolve(target);if(existsSync(dir)&&readdirSync(dir).length)throw new Error('Recovery target must be empty. Keep the original installation untouched.');
const b=readFileSync(source),phrase=readFileSync(passphraseFile,'utf8').replace(/\r?\n$/,'');if(b.length<53||b.subarray(0,8).toString()!=='JAWABAK1')throw new Error('Invalid Jawa backup.');
const d=createDecipheriv('aes-256-gcm',scryptSync(phrase,b.subarray(8,24),32),b.subarray(24,36));d.setAuthTag(b.subarray(36,52));const restored=Buffer.concat([d.update(b.subarray(52)),d.final()]);
mkdirSync(dir,{recursive:true,mode:0o700});const tmp=resolve(dir,'restore-check.sqlite');writeFileSync(tmp,restored,{mode:0o600,flag:'wx'});let db;
try{db=new DatabaseSync(tmp);if(Object.values(db.prepare('PRAGMA integrity_check').get())[0]!=='ok')throw new Error('Backup integrity check failed.');if(db.prepare('PRAGMA user_version').get().user_version!==1)throw new Error('Unsupported backup schema version.');for(const r of db.prepare('SELECT payload FROM stores').all()){const s=JSON.parse(r.payload);if(!s.settings||!Array.isArray(s.orders)||!Array.isArray(s.products))throw new Error('Invalid store records.');}if(!db.prepare("SELECT id FROM staff WHERE role='owner' AND disabled=0").get())throw new Error('Backup has no active owner.');db.exec('DELETE FROM sessions; DELETE FROM throttle; PRAGMA wal_checkpoint(TRUNCATE); PRAGMA journal_mode=DELETE;');db.close();db=undefined;renameSync(tmp,resolve(dir,'jawa.sqlite'));console.log('Recovery verified. Start Jawa with JAWA_DATA_DIR='+dir+' and sign in again.');}catch(e){if(db)db.close();for(const s of ['','-wal','-shm'])if(existsSync(tmp+s))unlinkSync(tmp+s);throw e;}
