import {useEffect,useState,type FormEvent,lazy,Suspense} from 'react';
import {createRoot} from 'react-dom/client';
import '../app/globals.css';
import '../app/pos.css';
import './web.css';
const Pos=lazy(()=>import('../app/pos')),Workspace=lazy(()=>import('../app/workspace')),OnlineOrder=lazy(()=>import('../app/online-order'));
type User={id:string;username:string;role:string};
type Session={user:User|null;setupRequired:boolean;mode:'restaurant'|'retail'};
async function call<T=unknown>(path:string,body?:unknown){const r=await fetch(path,{cache:'no-store',...(body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});const d=await r.json() as T&{error?:string};if(!r.ok)throw new Error(d.error||'Request failed.');return d;}
function App(){
 const [session,setSession]=useState<Session|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const path=window.location.pathname;
 useEffect(()=>{call<Session>('/api/session').then(setSession).catch(e=>setError(e.message));},[]);
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(busy)return;setBusy(true);setError('');const fields=Object.fromEntries(new FormData(e.currentTarget));try{if(session?.setupRequired)await call('/api/setup',fields);await call('/api/login',fields);window.location.assign('/');}catch(e){setError((e as Error).message);call<Session>('/api/session').then(setSession).catch(()=>{});}finally{setBusy(false);}};
 if(path.startsWith('/order/'))return <OnlineOrder mode={path.endsWith('/retail')?'retail':'restaurant'}/>;
 if(!session)return <main className="server-auth"><h1>Jawa POS</h1><p>{error||'Opening your store…'}</p>{error&&<button onClick={()=>window.location.reload()}>Retry connection</button>}</main>;
 if(!session.user)return <main className="server-auth"><div className="server-brand">j.</div><p className="server-eyebrow">JAWA {session.mode.toUpperCase()}</p><h1>{session.setupRequired?'Welcome to your store':'Welcome back'}</h1><p>{session.setupRequired?'Create your owner account to begin. Your records stay on your server.':'Sign in to open your register and store records.'}</p><form onSubmit={submit}>
 {session.setupRequired&&<label>Installation token<input name="token" required type="password" autoComplete="off"/><small>On your server, read the file data/setup-token. This token works only once.</small></label>}
 <label>Username<input name="username" required autoComplete="username" minLength={3} maxLength={80}/></label><label>Password<input name="password" type="password" required minLength={session.setupRequired?12:1} maxLength={128} autoComplete={session.setupRequired?'new-password':'current-password'}/></label>{error&&<p role="alert" className="server-error">{error}</p>}<button disabled={busy}>{busy?'Please wait…':session.setupRequired?'Create owner account':'Sign in'}</button></form><small>Server edition · CAD · Controlled pilot release</small></main>;
 return <><div className="server-toolbar"><a href={'/'+session.mode}>jawa <b>{session.mode}</b></a><span>{session.user.username} · {session.user.role}</span><a href="/admin">Account &amp; server</a><button onClick={async()=>{try{await call('/api/logout',{});window.location.assign('/login');}catch(e){setError((e as Error).message);}}}>Sign out</button>{error&&<span role="alert">{error}</span>}</div>{path==='/admin'?<Admin user={session.user}/>:path==='/manage'?<Workspace/>:<Pos mode={path==='/retail'?'retail':path==='/restaurant'?'restaurant':session.mode}/>}</>;
}
function Admin({user}:{user:User}){
 const [staff,setStaff]=useState<(User&{disabled:number})[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[reports,setReports]=useState<unknown[]>([]),[diagnostics,setDiagnostics]=useState<unknown>(null);
 const load=()=>{if(user.role==='owner')void call<{staff:(User&{disabled:number})[]}>('/api/admin/staff').then(d=>setStaff(d.staff)).catch(e=>setMessage(e.message));};useEffect(load,[user.role]);
 const action=async(fn:()=>Promise<void>)=>{if(busy)return;setBusy(true);setMessage('');try{await fn();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}};
 return <main className="server-admin"><header><p className="server-eyebrow">YOUR STORE, YOUR CONTROL</p><h1>Account &amp; server</h1><p>Manage staff access, recoverable backups and end-of-day records.</p></header>{message&&<p className="server-message" role="status">{message}</p>}
 <div className="server-admin-grid"><section><h2>Change your password</h2><form onSubmit={e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget));void action(async()=>{await call('/api/password',body);window.location.assign('/login');});}}><label>Current password<input name="currentPassword" type="password" required autoComplete="current-password"/></label><label>New password<input name="password" type="password" required minLength={12} maxLength={128} autoComplete="new-password"/></label><button disabled={busy}>Change password and sign out</button><small>This signs out all your sessions.</small></form></section>
 {user.role==='owner'&&<><section><h2>Staff access</h2><p>Managers can change store records. Cashiers can sell and handle orders. Kitchen staff can update preparation and printing. Staff can view shared store records; these are action permissions.</p><ul>{staff.map(s=><li key={s.id}><b>{s.username}</b> · {s.role} {s.disabled?'· Disabled':s.role!=='owner'&&<button disabled={busy} onClick={()=>void action(async()=>{await call('/api/admin/staff',{action:'disable',id:s.id});load();setMessage('Staff access revoked.');})}>Disable access</button>}</li>)}</ul><form onSubmit={e=>{e.preventDefault();const f=e.currentTarget,body=Object.fromEntries(new FormData(f));void action(async()=>{await call('/api/admin/staff',body);f.reset();load();setMessage('Staff account created.');});}}><label>New username<input name="username" required minLength={3} maxLength={80} autoComplete="off"/></label><label>Temporary password<input name="password" type="password" required minLength={12} maxLength={128} autoComplete="new-password"/></label><label>Role<select name="role"><option value="cashier">Cashier</option><option value="kitchen">Kitchen</option><option value="manager">Manager</option></select></label><button disabled={busy}>Add staff member</button></form></section>
 <section><h2>Encrypted backup</h2><p>Download a full database copy. Keep its passphrase separately. Restore into a fresh installation using the included recovery command.</p><form onSubmit={e=>{e.preventDefault();const f=e.currentTarget,body=Object.fromEntries(new FormData(f));void action(async()=>{const r=await fetch('/api/admin/backup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error((await r.json() as {error:string}).error);const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download='jawa-'+new Date().toISOString().slice(0,10)+'.jawabak';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);f.reset();setMessage('Encrypted backup downloaded. Keep the passphrase separately.');});}}><label>Backup passphrase<input name="passphrase" type="password" required minLength={16} maxLength={128} autoComplete="new-password"/></label><button disabled={busy}>Download encrypted backup</button></form><small>Automatic daily backups are kept on this server. Copy them off the server with the supplied restic instructions.</small></section>
 <section><h2>Reports &amp; diagnostics</h2><p>Closed business days use the store timezone and cutoff. Reports catch up after a restart and refresh after late adjustments.</p><button disabled={busy} onClick={()=>void action(async()=>{setReports((await call<{reports:unknown[]}>('/api/admin/reports')).reports);})}>Load daily summaries</button><button disabled={busy} onClick={()=>void action(async()=>{setDiagnostics(await call('/api/admin/diagnostics'));})}>Check server status</button>{reports.length>0?<pre>{JSON.stringify(reports,null,2)}</pre>:<p>No summaries loaded.</p>}{diagnostics!==null&&<pre>{JSON.stringify(diagnostics,null,2)}</pre>}</section></>}
 </div></main>;
}
createRoot(document.getElementById('root')!).render(<Suspense fallback={<main className="server-auth">Opening Jawa…</main>}><App/></Suspense>);
