import { channelOperation, type ChannelRequest } from './channels.ts';
import { newId } from './ids.ts';
import { canonical, extendedOperation, makeLines, queuePrint, type HeldCart, type DiningTable } from './pos-operations.ts';
export type Mode = 'retail'|'restaurant';
export type Product = {id:string;sku:string;name:string;category:string;mode:Mode;price:number;cost:number;stock:number;low:number;taxBps:number};
export type Line = {productId:string;name:string;sku:string;qty:number;price:number;cost:number;taxBps:number;tax:number;refunded:number;note?:string};
export type KitchenBatch = {id:string;lines:Line[];status:'new'|'preparing'|'ready'|'served';createdAt:string};
export type Order = {id:string;externalId?:string;paymentMethod?:'cash'|'external';number:number;mode:Mode;channel:string;reference:string;notes:string;callId?:string;tableId?:string;version?:number;batches?:KitchenBatch[];preparationStarted?:boolean;lines:Line[];subtotal:number;tax:number;total:number;createdAt:string;businessDate:string;paidAt?:string;paidBusinessDate?:string;shiftId?:string;status:'unpaid'|'paid'|'refunded'|'cancelled';kitchen:'none'|'new'|'preparing'|'ready'|'served'|'cancelled';};
export type Refund = {id:string;orderId:string;at:string;businessDate:string;shiftId:string;subtotal:number;tax:number;total:number;reason:string;lines:{productId:string;qty:number;restock:boolean}[]};
export type Movement = {id:string;productId:string;delta:number;reason:string;at:string;reference:string};
export type Shift = {id:string;openedAt:string;closedAt?:string;float:number;counted?:number;expected?:number;variance?:number;businessDate:string};
export type PrintJob = {id:string;orderId:string;kind:'kitchen'|'receipt';status:'pending'|'claimed'|'submitted'|'uncertain'|'confirmed';createdAt:string;confirmedAt?:string;claimId?:string;delivery?:'manual'|'bridge';event?:'order'|'addition'|'cancellation'|'reprint';snapshot?:Order};
export type Settings = {name:string;timezone:string;open:string;close:string;cutoff:string;closedDays:number[]};
export type CashMovement = {id:string;shiftId:string;at:string;businessDate:string;direction:'in'|'out';amount:number;reason:string};
export type Store = {settings:Settings;online?:{enabled:boolean;prepMinutes:number};channelRequests?:ChannelRequest[];cashMovements?:CashMovement[];voiceDrafts?:Record<string,string>;tables?:DiningTable[];holds?:HeldCart[];products:Product[];orders:Order[];refunds:Refund[];movements:Movement[];shifts:Shift[];prints:PrintJob[];audit:{id:string;at:string;action:string;detail:string}[];applied:Record<string,{fingerprint:string;result:string}>};
export type Operation = {id:string;type:string;[key:string]:unknown};
export const money=(n:number)=>new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(n/100);
export function emptyStore():Store{return {settings:{name:'Jawa training store',timezone:'America/Toronto',open:'09:00',close:'22:00',cutoff:'04:00',closedDays:[]},products:[],orders:[],refunds:[],movements:[],shifts:[],prints:[],audit:[],applied:{}};}
export function localParts(at:string,timezone:string){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23',weekday:'short'}).formatToParts(new Date(at));const p=Object.fromEntries(parts.map(x=>[x.type,x.value]));return {date:`${p.year}-${p.month}-${p.day}`,time:`${p.hour}:${p.minute}`,day:['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].indexOf(p.weekday)};}
export function businessDate(at:string,s:Settings){const p=localParts(at,s.timezone);return p.time<s.cutoff?new Date(Date.parse(p.date+'T12:00:00Z')-86400000).toISOString().slice(0,10):p.date;}
export function isOpen(at:string,s:Settings){const p=localParts(at,s.timezone);const overnight=s.close<s.open;const day=overnight&&p.time<s.close?(p.day+6)%7:p.day;return !s.closedDays.includes(day)&&(overnight?(p.time>=s.open||p.time<s.close):(p.time>=s.open&&p.time<s.close));}
export function activeShift(s:Store){return s.shifts.find(x=>!x.closedAt);}
export function expectedCash(s:Store,shift:Shift){return shift.float+s.orders.filter(o=>o.shiftId===shift.id&&o.paidAt&&o.paymentMethod!=='external').reduce((n,o)=>n+o.total,0)-s.refunds.filter(r=>r.shiftId===shift.id).reduce((n,r)=>n+r.total,0)+(s.cashMovements??[]).filter(m=>m.shiftId===shift.id).reduce((n,m)=>n+(m.direction==='in'?m.amount:-m.amount),0);}
function assert(ok:unknown,msg:string):asserts ok {if(!ok)throw new Error(msg);}
function str(v:unknown,name:string,max=200){assert(typeof v==='string'&&v.trim().length>0&&v.length<=max,`Enter a valid ${name}.`);return v.trim();}
function integer(v:unknown,name:string,min=0,max=100000000){assert(Number.isSafeInteger(v)&&Number(v)>=min&&Number(v)<=max,`Invalid ${name}.`);return Number(v);}
function clock(v:unknown){assert(typeof v==='string'&&/^([01]\d|2[0-3]):[0-5]\d$/.test(v),'Invalid store time.');return v;}
function product(s:Store,id:unknown){const p=s.products.find(x=>x.id===id);assert(p,'Product not found.');return p;}
function order(s:Store,id:unknown){const o=s.orders.find(x=>x.id===id);assert(o,'Order not found.');return o;}
function shift(s:Store){const sh=activeShift(s);assert(sh,'Open a cash shift first.');return sh;}
function movement(s:Store,p:Product,delta:number,reason:string,at:string,ref:string){assert(p.stock+delta>=0,'Not enough stock for '+p.name+'.');assert(p.stock+delta<=1000000,'Stock limit exceeded.');p.stock+=delta;s.movements.push({id:newId(),productId:p.id,delta,reason,at,reference:ref});}
function sampleProducts():Product[]{return [
['RET-001','Canvas tote','Accessories',1800,650,24],['RET-002','Ceramic mug','Homewares',1600,600,18],['RET-003','Pocket notebook','Stationery',850,250,32],['RET-004','Steel bottle','Accessories',2800,1100,12],['RET-005','Desk planter','Homewares',2200,900,8],['RET-006','Gift wrap','Stationery',450,120,5],
['FOOD-001','Classic burger','Mains',1450,480,30],['FOOD-002','Garden bowl','Mains',1250,390,24],['FOOD-003','Margherita pizza','Mains',1650,520,20],['FOOD-004','French fries','Sides',550,140,40],['FOOD-005','Iced latte','Drinks',575,160,35],['FOOD-006','Lemon soda','Drinks',425,95,6]
].map((r,i)=>({id:`sample-${i+1}`,sku:String(r[0]),name:String(r[1]),category:String(r[2]),mode:i<6?'retail':'restaurant',price:Number(r[3]),cost:Number(r[4]),stock:Number(r[5]),low:8,taxBps:1300}));}
export function applyOperation(original:Store,op:Operation,at=new Date().toISOString()):{state:Store;result:string;duplicate:boolean}{
 const id=str(op.id,'operation ID',100);assert(/^[a-zA-Z0-9_-]+$/.test(id),'Invalid operation ID.');const fingerprint=canonical(op);
 assert(!['__proto__','constructor','prototype'].includes(id),'Invalid operation ID.');
 if(Object.hasOwn(original.applied,id)){assert(canonical(JSON.parse(original.applied[id].fingerprint))===fingerprint,'Operation ID already used for another request.');return {state:original,result:original.applied[id].result,duplicate:true};}
 assert(original.audit.length<10000,'Training capacity reached. Export your records.');const s=structuredClone(original);let result='Saved';
 switch(op.type){
 case 'seed':{assert(!s.products.length&&!s.orders.length,'Sample catalog can only be loaded into an empty store.');s.products=sampleProducts();s.tables??=[1,2,3,4,5,6].map(n=>({id:'table-'+n,name:'Table '+n,seats:n<5?2:4}));s.products.forEach(p=>s.movements.push({id:newId(),productId:p.id,delta:p.stock,reason:'Sample opening stock',at,reference:id}));result='12 sample products loaded';break;}
 case 'openShift':{assert(!activeShift(s),'A shift is already open.');s.shifts.push({id,openedAt:at,float:integer(op.float,'opening float'),businessDate:businessDate(at,s.settings)});result='Shift opened';break;}
 case 'cashMovement':{const sh=shift(s);assert(op.direction==='in'||op.direction==='out','Choose cash in or cash out.');const amount=integer(op.amount,'cash amount',1,100000000);const reason=str(op.reason,'cash movement reason');assert(op.confirmed===true,'Confirm the physical cash movement.');assert(op.direction==='in'||amount<=expectedCash(s,sh),'Cash out exceeds expected cash in the drawer.');s.cashMovements??=[];s.cashMovements.push({id,shiftId:sh.id,at,businessDate:businessDate(at,s.settings),direction:op.direction,amount,reason});result=(op.direction==='in'?'Cash added':'Cash removed')+' · '+money(amount);break;}
 case 'closeShift':{const sh=shift(s);assert(!s.orders.some(o=>o.status==='unpaid'),'Settle or cancel unpaid orders before closing.');sh.counted=integer(op.counted,'counted cash');sh.expected=expectedCash(s,sh);sh.variance=sh.counted-sh.expected;sh.closedAt=at;result='Shift closed · variance '+money(sh.variance);break;}
 case 'product':{assert(s.products.length<2000,'Product capacity reached.');const sku=str(op.sku,'SKU',80);assert(!s.products.some(p=>p.sku.toLowerCase()===sku.toLowerCase()),'SKU already exists.');assert(op.mode==='retail'||op.mode==='restaurant','Choose a product type.');const stock=integer(op.stock,'stock',0,1000000);const p:Product={id,sku,name:str(op.name,'name',120),category:str(op.category,'category',60),mode:op.mode,price:integer(op.price,'price',1,1000000),cost:integer(op.cost,'cost',0,1000000),stock:0,low:integer(op.low,'low stock threshold',0,1000000),taxBps:integer(op.taxBps,'tax rate',0,3000)};s.products.push(p);movement(s,p,stock,'Opening stock',at,id);result='Product added';break;}
 case 'stock':{const p=product(s,op.productId);const count=integer(op.count,'stock count',0,1000000);movement(s,p,count-p.stock,str(op.reason,'stock adjustment reason'),at,id);result='Stock count saved';break;}
 case 'receive':{assert(Array.isArray(op.rows)&&op.rows.length>0&&op.rows.length<=100,'Review 1–100 inventory rows.');const seen=new Set<string>();for(const row of op.rows as {sku:string;qty:number}[]){const sku=str(row.sku,'SKU',80);assert(!seen.has(sku.toLowerCase()),'Duplicate SKU in import.');seen.add(sku.toLowerCase());const p=s.products.find(p=>p.sku.toLowerCase()===sku.toLowerCase());assert(p,'Unknown SKU: '+sku);movement(s,p,integer(row.qty,'received quantity',1,1000000),'Reviewed inventory import',at,id);}result='Inventory received';break;}
 case 'order':{shift(s);assert(s.orders.length<1000,'Training order capacity reached. Export your records.');assert(op.mode==='retail'||op.mode==='restaurant','Invalid register.');assert(Array.isArray(op.items)&&op.items.length>0&&op.items.length<=100,'Add 1–100 items.');const channel=op.channel==='phone'?'phone':'register';if(channel==='phone'){if(op.quoteId)assert(typeof op.callId==='string'&&s.voiceDrafts?.[op.callId]===op.quoteId,'This quote was replaced. Read back the latest quote.');assert(isOpen(at,s.settings),'The store is closed for phone orders.');if(op.callId)assert(!s.orders.some(o=>o.callId===op.callId),'An order already exists for this call.');}assert(op.confirmed===true,'Confirm the order before submitting.');const lines=makeLines(s,op.items,op.mode);if(op.holdId){assert(s.holds?.some(h=>h.id===op.holdId&&h.mode===op.mode),'This held cart was already completed or removed.');s.holds=(s.holds??[]).filter(h=>h.id!==op.holdId);}if(op.tableId){assert(op.mode==='restaurant'&&s.tables?.some(t=>t.id===op.tableId),'Table not found.');assert(!s.orders.some(o=>o.tableId===op.tableId&&o.status==='unpaid'),'This table already has an open check. Open that check to add items.');}const subtotal=lines.reduce((n,l)=>n+l.qty*l.price,0),tax=lines.reduce((n,l)=>n+l.tax,0);assert(subtotal+tax<=100000000,'Order total exceeds training limit.');if(op.expectedTotal!==undefined)assert(op.expectedTotal===subtotal+tax,'Price changed. Read back a new quote.');const paid=op.tender==='cash';assert(op.tender==='cash'||(op.tender==='unpaid'&&op.mode==='restaurant'),'Only cash or an unpaid restaurant order is supported.');if(paid)assert(integer(op.cashReceived,'cash received')>=subtotal+tax,'Cash received is less than total.');const o:Order={id,number:s.orders.length+1001,mode:op.mode,channel,reference:typeof op.reference==='string'?op.reference.slice(0,100):'',notes:typeof op.notes==='string'?op.notes.slice(0,1000):'',lines,subtotal,tax,total:subtotal+tax,createdAt:at,businessDate:businessDate(at,s.settings),status:paid?'paid':'unpaid',kitchen:op.mode==='restaurant'?'new':'none'};if(paid){o.paidAt=at;o.paidBusinessDate=businessDate(at,s.settings);o.shiftId=shift(s).id;}if(typeof op.callId==='string')o.callId=op.callId;if(typeof op.tableId==='string')o.tableId=op.tableId;o.version=1;if(o.mode==='restaurant')o.batches=[{id,lines:structuredClone(lines),status:'new',createdAt:at}];s.orders.push(o);for(const l of lines)movement(s,product(s,l.productId),-l.qty,'Order accepted',at,id);queuePrint(s,o,at,op.mode==='restaurant'?'kitchen':'receipt');result=String(o.number);break;}
 case 'pay':{const o=order(s,op.orderId);assert(o.status==='unpaid','Order is no longer unpaid.');assert(integer(op.cashReceived,'cash received')>=o.total,'Cash received is less than total.');o.status='paid';o.paidAt=at;o.paidBusinessDate=businessDate(at,s.settings);o.shiftId=shift(s).id;queuePrint(s,o,at,'receipt');result='Payment recorded';break;}
 case 'kitchen':{const o=order(s,op.orderId);assert(o.mode==='restaurant'&&o.status!=='cancelled'&&o.status!=='refunded','Order is closed.');const next:Record<string,string>={new:'preparing',preparing:'ready',ready:'served'};o.batches??=[{id:o.id,lines:structuredClone(o.lines),status:o.kitchen as 'new'|'preparing'|'ready'|'served',createdAt:o.createdAt}];const selected=op.batchId?o.batches.filter(b=>b.id===op.batchId):o.batches.filter(b=>b.status===o.kitchen);assert(selected.length&&selected.every(b=>next[b.status]===op.status),'Kitchen status changed. Refresh and try again.');for(const b of selected)b.status=op.status as 'preparing'|'ready'|'served';if(op.status==='preparing')o.preparationStarted=true;o.kitchen=o.batches.some(b=>b.status==='new')?'new':o.batches.some(b=>b.status==='preparing')?'preparing':o.batches.some(b=>b.status==='ready')?'ready':'served';result='Kitchen updated';break;}
 case 'cancel':{const o=order(s,op.orderId);assert(o.status==='unpaid','Only unpaid orders can be cancelled.');const reason=str(op.reason,'cancellation reason');if(o.mode==='retail'||(o.kitchen==='new'&&!o.preparationStarted))for(const l of o.lines)movement(s,product(s,l.productId),l.qty,'Cancelled before preparation',at,o.id);o.status='cancelled';o.kitchen='cancelled';o.notes=(o.notes+'\nCancellation: '+reason).trim();queuePrint(s,o,at,o.mode==='restaurant'?'kitchen':'receipt','cancellation');result='Order cancelled: '+reason;break;}
 case 'refund':{const o=order(s,op.orderId);assert(o.status==='paid','Order is not refundable.');assert(o.paymentMethod!=='external','Refund this order on its original delivery platform. Cash refunds are blocked.');const sh=shift(s);const reason=str(op.reason,'refund reason');assert(Array.isArray(op.items)&&op.items.length>0,'Select items to refund.');let subtotal=0,tax=0;const seen=new Set<string>();const lines=(op.items as {productId:string;qty:number;restock:boolean}[]).map(row=>{const l=o.lines.find(l=>l.productId===row.productId);assert(l,'Original item not found.');assert(!seen.has(l.productId),'Duplicate refund line.');seen.add(l.productId);const qty=integer(row.qty,'refund quantity',1,l.qty-l.refunded);const before=Math.round(l.tax*l.refunded/l.qty),after=Math.round(l.tax*(l.refunded+qty)/l.qty);subtotal+=qty*l.price;tax+=after-before;l.refunded+=qty;if(row.restock===true)movement(s,product(s,l.productId),qty,'Refund restock',at,o.id);return {productId:l.productId,qty,restock:row.restock===true};});s.refunds.push({id,orderId:o.id,at,businessDate:businessDate(at,s.settings),shiftId:sh.id,subtotal,tax,total:subtotal+tax,reason,lines});if(o.lines.every(l=>l.refunded===l.qty)){o.status='refunded';if(o.mode==='restaurant'&&o.kitchen!=='served'){o.kitchen='cancelled';queuePrint(s,{...o,notes:(o.notes+'\nFully refunded: '+reason).trim()},at,'kitchen','cancellation');}}result='Refund recorded · '+money(subtotal+tax);break;}
 case 'printClaim':{const job=s.prints.find(x=>x.id===op.jobId);assert(job,'Print job not found.');assert(job.status==='pending','Print job already claimed.');const o=order(s,job.orderId);assert(job.event==='cancellation'||job.event==='reprint'||(o.status!=='cancelled'&&o.status!=='refunded'),'Order is closed.');job.snapshot??=structuredClone(o);job.status='claimed';job.claimId=id;job.delivery=op.delivery==='manual'?'manual':'bridge';result='Print job claimed';break;}
 case 'printResult':{const job=s.prints.find(x=>x.id===op.jobId);assert(job&&job.claimId===op.claimId,'Invalid print claim.');assert(job.status==='claimed','Print job already resolved.');assert(op.status==='submitted'||op.status==='uncertain','Invalid printer result.');job.status=op.status;result=op.status==='submitted'?'Sent to printer; paper unverified':'Printer outcome uncertain';break;}
 case 'printConfirm':{const job=s.prints.find(x=>x.id===op.jobId);assert(job,'Print job not found.');assert(['claimed','submitted','uncertain'].includes(job.status),'Reserve or reconcile this ticket before confirming paper.');job.status='confirmed';job.confirmedAt=at;result='Paper output confirmed';break;}
 case 'settings':{assert(!activeShift(s),'Close the shift before changing business hours.');const tz=str(op.timezone,'time zone',80);assert(['America/Toronto','America/Vancouver','America/Edmonton','America/Winnipeg','America/Halifax','America/St_Johns'].includes(tz),'Unsupported time zone.');const open=clock(op.open),close=clock(op.close),cutoff=clock(op.cutoff);assert(open!==close,'Opening and closing times must differ.');assert(Array.isArray(op.closedDays)&&op.closedDays.every(v=>Number.isInteger(v)&&Number(v)>=0&&Number(v)<=6),'Invalid closed days.');s.settings={name:str(op.name,'store name',100),timezone:tz,open,close,cutoff,closedDays:op.closedDays as number[]};result='Store settings saved';break;}
 default:{const channelResult=channelOperation(s,{...op,businessDate:businessDate(at,s.settings)},at);const extended=channelResult??extendedOperation(s,op,at);assert(extended!==undefined,'Unknown operation.');result=extended;break;}
 }
 s.audit.push({id,at,action:op.type,detail:result});s.applied[id]={fingerprint,result};return {state:s,result,duplicate:false};
}
export function report(s:Store,from:string,to:string,mode?:Mode){const orderModes=new Map(s.orders.map(o=>[o.id,o.mode]));const orders=s.orders.filter(o=>(!mode||o.mode===mode)&&o.paidAt&&o.paidBusinessDate!>=from&&o.paidBusinessDate!<=to);const refunds=s.refunds.filter(r=>(!mode||orderModes.get(r.orderId)===mode)&&r.businessDate>=from&&r.businessDate<=to);const gross=orders.reduce((n,o)=>n+o.subtotal,0),returned=refunds.reduce((n,r)=>n+r.subtotal,0),tax=orders.reduce((n,o)=>n+o.tax,0)-refunds.reduce((n,r)=>n+r.tax,0);return {orders,refunds,gross,returned,net:gross-returned,tax,cash:orders.filter(o=>o.paymentMethod!=='external').reduce((n,o)=>n+o.total,0)-refunds.reduce((n,r)=>n+r.total,0),external:orders.filter(o=>o.paymentMethod==='external').reduce((n,o)=>n+o.total,0),count:orders.length};}
