"""Build complete, secret-free source distributions from tracked/eligible source.
Run from the repository root after validation. Does not publish or configure services.
"""
import hashlib
import json
from pathlib import Path
import subprocess
import zipfile

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'kits'
OUTPUT.mkdir(parents=True, exist_ok=True)
paths = sorted(set(subprocess.check_output(['git', 'ls-files', '-co', '--exclude-standard', '-z'], cwd=ROOT).decode().split('\0')) - {''})
exclude = {'kits', 'node_modules', '.git', 'dist', '.wrangler', '.sites-runtime', '.agents', '.codex', 'outputs', 'work'}
files = {}
for relative in paths:
    path = Path(relative)
    if path.parts[0] in exclude or relative.startswith('public/downloads/'):
        continue
    if path.name.startswith('.env') and path.name != '.env.example':
        continue
    if any(part == '__pycache__' for part in path.parts) or path.suffix in ('.pyc', '.sqlite', '.pem'):
        continue
    if not (ROOT / path).is_file() or (ROOT / path).is_symlink():
        continue
    files[relative] = (ROOT / path).read_bytes()
# Keep logical bindings but remove the maintained deployment's lifecycle identifier.
files['.openai/hosting.json'] = b'{"d1":"DB","r2":null}\n'
# Generated by Next/Vinext during install/build; include a portable declaration.
files['next-env.d.ts'] = b'/// <reference types="next" />\n/// <reference types="next/image-types/global" />\n'
if not (ROOT / 'dist/server/index.js').is_file():
    raise RuntimeError('Build the Worker before packaging kits.')
for path in sorted((ROOT / 'dist').rglob('*')):
    if not path.is_file() or path.is_symlink():
        continue
    relative = path.relative_to(ROOT / 'dist').as_posix()
    # Do not nest the downloadable kits inside their own compiled asset copy.
    if relative.startswith('client/downloads/') or path.name.startswith('.env'):
        continue
    data = path.read_bytes()
    if relative == '.openai/hosting.json':
        data = b'{"d1":"DB","r2":null}\n'
    files['compiled/' + relative] = data
required = ['app/restaurant/page.tsx', 'app/retail/page.tsx', 'app/pos.tsx', 'lib/engine.ts', 'pnpm-lock.yaml', 'drizzle/0000_faulty_pandemic.sql', 'integrations/voice/agent.py', 'integrations/printer/bridge.py', 'docs/VALIDATION.md', 'public/ocr/lang/eng.traineddata.gz']
for path in required:
    if path not in files:
        raise RuntimeError('Required source missing: ' + path)
archives = []
for mode in ('Restaurant', 'Retail'):
    folder = 'Jawa_' + mode + '_Source_Kit'
    kit = dict(files)
    kit['KIT_START_HERE.md'] = (f'# Jawa {mode} source kit\n\nStart with `README.md`, then `docs/START_HERE.md` and `docs/DEVELOPER_SETUP.md`.\n\nPreferred application route: `/{mode.lower()}`. This complete source distribution\nretains both registers and the shared engine, database, back office, adapters,\ntests, OCR assets, licences and research. Use one deployment to share records.\n\nThe `compiled/` folder contains the built web Worker and client assets, plus\nstaged schema files. It requires a compatible host, authentication and D1; it is\nnot a static website or native installer. Source-kit downloads are excluded from\nthat asset copy to avoid recursive archives.\n\nThis is a development/training kit, not a fully activated commercial POS.\nSee the feature matrix and validation record for exact status.\n').encode()
    manifest = {'kit': mode, 'release': '0.2.0', 'entryRoute': '/' + mode.lower(), 'files': {p: hashlib.sha256(data).hexdigest() for p, data in sorted(kit.items())}}
    kit['SOURCE_MANIFEST.json'] = (json.dumps(manifest, indent=2) + '\n').encode()
    target = OUTPUT / (folder + '.zip')
    with zipfile.ZipFile(target, 'w', compression=zipfile.ZIP_DEFLATED, compresslevel=6) as archive:
        for path, data in sorted(kit.items()):
            info = zipfile.ZipInfo(folder + '/' + path, date_time=(2026, 9, 10, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            archive.writestr(info, data)
    with zipfile.ZipFile(target) as archive:
        if archive.testzip() is not None:
            raise RuntimeError('Archive CRC check failed')
        for path, digest in manifest['files'].items():
            if hashlib.sha256(archive.read(folder + '/' + path)).hexdigest() != digest:
                raise RuntimeError('Archive manifest mismatch: ' + path)
        if any(n.endswith('/.env') or '/node_modules/' in n or '/.git/' in n for n in archive.namelist()):
            raise RuntimeError('Excluded private or generated files present')
    archives.append({'file': target.name, 'bytes': target.stat().st_size, 'sha256': hashlib.sha256(target.read_bytes()).hexdigest(), 'sourceFiles': len(kit)})
(OUTPUT / 'SHA256SUMS.txt').write_text(''.join(row['sha256'] + '  ' + row['file'] + '\n' for row in archives))
(OUTPUT / 'KIT_INDEX.json').write_text(json.dumps(archives, indent=2) + '\n')
print(json.dumps(archives, indent=2))
